filter:
    excluded_paths:
        - tests/*
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_analyzer: true
    php_mess_detector: true
    external_code_coverage: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cpd: true
    php_pdepend: true
    sensiolabs_security_checker: true
build:
    environment:
        php:
            version: 5.6, 7.0
            ini:
                'date.timezone': 'US/Pacific'
